package com.yugen.mobile.service.impl;

import com.google.gson.JsonObject;
import com.yugen.mobile.hsqldb.DBManger;
import com.yugen.mobile.hsqldb.SqlBuilder;
import com.yugen.mobile.service.RequestService;
import org.springframework.stereotype.Service;

/**
 * Description:
 * <p>
 * Created by A.T on 2018/06/09
 */
@Service
public class RequestServiceImpl implements RequestService {
    private static final String REQUEST_TABLE = "cloud_request";
    private static final String CREATE_REQUEST = "CREATE TABLE " + REQUEST_TABLE + "  (" +
            "    id INTEGER GENERATED BY DEFAULT AS IDENTITY," +
            "    type VARCHAR(10)," +
            "    applyno VARCHAR(64)," +
            "    ecordercode VARCHAR(32)," +
            "    content VARCHAR(8192)," +
            "    sign VARCHAR(255)," +
            "    timestamp BIGINT" +
            ")";

    private static final String INSERT_REQUEST = "INSERT INTO " + REQUEST_TABLE +  " (type, applyno, ecordercode, content, sign, timestamp)";
    private static final String DUMP_REQUEST = "SELECT * FROM " + REQUEST_TABLE +  " ";

    public void create(JsonObject request) {
        String sql = SqlBuilder.build(INSERT_REQUEST)
                .valueBegin(request)
                .setString("type")
                .setString("applyno")
                .setString("ecordercode")
                .setString("content")
                .setString("sign")
                .setLong("timestamp")
                .valuesEnd().toString();

        DBManger.executeUpdate(sql);
    }

    @Override
    public String dumpTable() {
        return DBManger.dump(DUMP_REQUEST);
    }
}
